-- Synthetic shipment rating schema (FedEx-inspired demo)
-- Run as RATING user after creating the schema user.

CREATE TABLE zone_matrix (
    origin_prefix   VARCHAR2(3) NOT NULL,
    dest_prefix     VARCHAR2(3) NOT NULL,
    zone_code       NUMBER(2)   NOT NULL,
    CONSTRAINT pk_zone_matrix PRIMARY KEY (origin_prefix, dest_prefix)
);

CREATE TABLE service_base_rate (
    zone_code       NUMBER(2)   NOT NULL,
    service_code    VARCHAR2(3) NOT NULL,
    base_amount     NUMBER(8,2) NOT NULL,
    CONSTRAINT pk_service_base_rate PRIMARY KEY (zone_code, service_code)
);

CREATE TABLE account_tier (
    account_id      VARCHAR2(20) NOT NULL,
    tier_code       VARCHAR2(10) NOT NULL,
    CONSTRAINT pk_account_tier PRIMARY KEY (account_id)
);

CREATE TABLE rating_audit (
    rating_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_ref    VARCHAR2(30),
    service_code    VARCHAR2(3),
    total_amount    NUMBER(10,2),
    error_code      NUMBER,
    rated_at        TIMESTAMP DEFAULT SYSTIMESTAMP
);
